development:
  adapter: postgresql
  encoding: unicode
  database: appsec_california_2014_development


test:
  adapter: postgresql
  encoding: unicode
  database: appsec_california_2014_test

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: appsec_california_2014_production
  pool: 5
  username: appsec_california_2014
  password: <%= ENV['DATABASE_PASSWORD'] %>
